### ISSUE TITLE
dnsmasq doesn't resolve .local domains

### ISSUE THREAD

**Issue by jostyee** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#180] opened 2022-10-20 16:16 UTC
After installation, I get default settings as below:
```
[/local/][::]:553
[/localdomain/][::]:553
```

and dnsmasq is listening on port 553 correctly. 
```
nslookup my-mbp.local 192.168.1.1:553
Server:    192.168.1.1
Address 1: 192.168.1.1 Router.local

Name:      my-mbp.local
Address 1: 192.168.1.4 my-mbp.local
```

But somehow the requests to lan devices are leaking to upstream server
<img width="427" alt="image" src="https://user-images.githubusercontent.com/88564/197003025-cd0bdacb-c8bc-4f91-a069-5503036b7dbf.png">

Is there anyway I can debug it? Thanks in advance.

**Comment by jumpsmm7** [comment] 2022-10-20 20:42
@jostyee , Sure please share a screenshot of your adguardhome upstream configuration and  Private reverse resolver configuration sections. 

The weird thing is it shows your request being sent to nextdns. Also if you don't mind, please share the contents of your AdGuardHome.yaml 

e.g. `cat /opt/etc/AdGuardHome/AdGuardHome.yaml`

**Comment by jumpsmm7** [comment] 2022-10-20 23:54
@jostyee 

Here is a thread for you to take a look at -

https://www.snbforums.com/threads/adguard-blocked-local-domain-queries.81284/

**Comment by jostyee** [comment] 2022-10-21 01:34
@jumpsmm7 my upstream/rDNS config part:

```
  upstream_dns:
    - '[/router.asus.com/][::]:553'
    - '[/www.asusnetwork.net/][::]:553'
    - '[/www.asusrouter.com/][::]:553'
    - '[/use-application-dns.net/][::]:553'
    - '[/dns.resolver.arpa/][::]:553'
    - '[/local/][::]:553'
    - '[/localdomain/][::]:553'
    - '[//][::]:553'
    - https://dns.nextdns.io/redacted
    - [/plex.direct/]1.1.1.1
  ...
  local_ptr_upstreams:
    - '[::]:553'
    - '[/10.in-addr.arpa/][::]:553'
    - '[/168.192.in-addr.arpa/][::]:553'
```

**Comment by jostyee** [comment] 2022-10-21 01:41
I guess AdGuard Home doesn't forward local requests to :553 ?

**Comment by jumpsmm7** [comment] 2022-10-21 01:41
> @jumpsmm7 my upstream/rDNS config part:
> 
> ```
>   upstream_dns:
>     - '[/router.asus.com/][::]:553'
>     - '[/www.asusnetwork.net/][::]:553'
>     - '[/www.asusrouter.com/][::]:553'
>     - '[/use-application-dns.net/][::]:553'
>     - '[/dns.resolver.arpa/][::]:553'
>     - '[/local/][::]:553'
>     - '[/localdomain/][::]:553'
>     - '[//][::]:553'
>     - [/plex.direct/]1.1.1.1
>     - https://dns.nextdns.io/redacted
>   ...
>   local_ptr_upstreams:
>     - '[::]:553'
>     - '[/10.in-addr.arpa/][::]:553'
>     - '[/168.192.in-addr.arpa/][::]:553'
> ```

try changing from .local  to something like ".lan" and remove the localdomain line from your upstream. see what happens, tell me if it fixes the issue. The problem i think is coming from .local being intended for a ZERO configuration DNS, not an actual DNS resolver. IEFT says it is for special use cases as such. Meaning it can leak upstream if you are not careful. I am just requesting you to test it out to see if the issue goes away.

**Comment by jumpsmm7** [comment] 2022-10-21 01:43
It is intended for multicast networking, which means it can leak upstream. 

https://en.wikipedia.org/wiki/.local

**Comment by jumpsmm7** [comment] 2022-10-21 01:43
local networks are intended to be unicast, (with the exception of IPV6). meaning .local can communicate over ipv6 networks for neighbor solicitations.

**Comment by jumpsmm7** [comment] 2022-10-21 01:46
`The [Internet Engineering Task Force](https://en.wikipedia.org/wiki/Internet_Engineering_Task_Force) (IETF) reserves the use of the domain name label .local as a [special-use domain name](https://en.wikipedia.org/wiki/Special-use_domain_name) for hostnames in local area networks that can be resolved via the [Multicast DNS](https://en.wikipedia.org/wiki/Multicast_DNS) name resolution protocol.[[2]](https://en.wikipedia.org/wiki/.local#cite_note-rfc6762-2) Any DNS query for a name ending with the label local must be sent to the mDNS IPv4 link-local multicast address 224.0.0.251, or its IPv6 equivalent ff02::fb. A domain name ending in .local may be resolved concurrently via other mechanisms, for example, unicast DNS.`

**Comment by jumpsmm7** [comment] 2022-10-21 01:54
To sum it up-From what I read, the whole issue may be being caused by your use of the domain name ".local" which can be resolved by both multicast DNS and unicast DNS concurrently. So the issue doesn't reside with adguardhome. AdGuardHome is adhering to the IEFT standards. Here you are experiencing an unfortunate side effect of using the domain name of ".local" and "localdomain".

**Comment by jostyee** [comment] 2022-10-21 02:07
Sorry for being noob but after I changed router's domain name to `lan` I can't connect other devices by local domains any longer.
<img width="653" alt="image" src="https://user-images.githubusercontent.com/88564/197094174-b568bf1d-095b-4205-89d2-eb96aa9f8691.png">

```
❯ ping joes-mbp.lan
ping: cannot resolve joes-mbp.lan: Unknown host
❯ hostname
joes-mbp.lan
```

**Comment by jumpsmm7** [comment] 2022-10-21 02:12
@jostyee 
This is correct:
![image](https://user-images.githubusercontent.com/49514613/197094627-92bc31fa-ef37-42ed-ac5b-a8bbc4f833d1.png)

Make sure you save it in the Web UI.

Next you need to edit adguardhome. Change the values from the image in your upstream section. Save it.

![image](https://user-images.githubusercontent.com/49514613/197095022-84197f2e-7d87-48f4-ab2a-6d02674c59b4.png)


then issue the SSH terminal command 

`service restart_AdGuardHome`

**Comment by jostyee** [comment] 2022-10-21 02:16
@jumpsmm7 I've already modified my agh config as you suggested, even restarted router, but it's just not working. :-(

**Comment by jumpsmm7** [comment] 2022-10-21 02:20
> @jumpsmm7 I've already modified my agh config as you suggested, even restarted router, but it's just not working. :-(

![image](https://user-images.githubusercontent.com/49514613/197096180-315c9851-4cc5-497d-a5e1-d273afddecc8.png)

**Comment by jumpsmm7** [comment] 2022-10-21 02:25
That is all the feedback I have, if none of it works, then there is something Unique about your setup that neither one of us understands. 

You have to dig into adguardhomes configuration wiki and figure it out on your own by comparing their guide to your setup. feel free to share what you find. As far as I am aware of, I have the installer setup per their configuration method following standard methods.

**Closed** 2022-10-21 02:26 UTC
Labels: question

**Comment by jostyee** [comment] 2022-10-21 02:32
@jumpsmm7 thanks for your patience, I'm really grateful. Will report back later if I figure out the reason.

**Comment by jostyee** [comment] 2022-10-21 02:35
@jumpsmm7 sorry but one more question, does the order of `upstream_dns` matter as you said at https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/issues/180#issuecomment-1286372307 ? I'm using `Parallel requests`

**Comment by jumpsmm7** [comment] 2022-10-21 02:40
Parallel requests and order might definitely have something to do with it. you are welcome to play around with it. That is why i mentions moving the order around to see if it changes anything.  However their wiki says otherwise. 
See the order they list things and their logic on how the responses should be handled-
![image](https://user-images.githubusercontent.com/49514613/197098612-c6064b21-1747-4c08-9390-e8603eb28321.png)

This leads me to think something may be broken upstream with AdGuardHome.

**Comment by jumpsmm7** [comment] 2022-10-21 02:43
@jostyee 

if it is not too much trouble to ask, how are you making this look up request.

https://user-images.githubusercontent.com/88564/197094685-dbcaa322-72d9-4a17-a0eb-c88172303209.png

is the requesting client connected within onehop of the network, or are you connected remotely making the request? Remote connections cannot resolve local addresses, which is an intended safety feature of adguardhome.

**Comment by jostyee** [comment] 2022-10-21 02:56
@jumpsmm7 I restarted all my devices & it works now, maybe need to do DHCP lease manually.
<img width="336" alt="image" src="https://user-images.githubusercontent.com/88564/197100724-42e70421-1c34-4989-8671-6ee3fb1a1ff9.png">

Thanks again for being so helpful. :-)

**Comment by jumpsmm7** [comment] 2022-10-21 03:16
> @jumpsmm7 I restarted all my devices & it works now, maybe need to do DHCP lease manually. <img alt="image" width="336" src="https://user-images.githubusercontent.com/88564/197100724-42e70421-1c34-4989-8671-6ee3fb1a1ff9.png">
> 
> Thanks again for being so helpful. :-)

@jostyee

For future reference, remember to steer clear of using .local . You were right about the client leases needing to be refreshed. Sometimes rebooting the router is simple enough to do the job, but sometimes it isnt.
